import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import fs from 'fs';
import path from 'path';const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../..');const SP = process.env.SP||path.join(ROOT,'data-build','smoke');fs.mkdirSync(SP,{recursive:true});
const html0 = fs.readFileSync(process.argv[2] || ''+ROOT+'/index.html','utf8');
const three = fs.readFileSync(path.join(ROOT,'node_modules/three/build/three.min.js'),'utf8');
// expose debug handles
const html = html0.replace(/\}\)\(\);\s*<\/script>\s*<\/html>\s*$/, `window.__D={SPOTS,STATIONS,renderer,scene,camera,get S(){return S},set S(v){S=v},F,start,update,render,updChunks,walk,chunks,cgrid,K,setJoy:(x,y)=>{jx=x;jy=y;},setYaw:v=>{yaw=v},setPitch:v=>{pitch=v},get yaw(){return yaw},get nearSpot(){return nearSpot},mainDown,mainUp,rodAction,setDrag,aimTarget,spotAt,travel,nearestStation,routesFrom,openMenu,closeSheet,snapCam,get NET(){return NET},get RIDE(){return RIDE},mount,dismount,buyVeh,setDest,plans,renderTab,setTab:(t,m)=>{tab=t;if(m)mapView=m;},vehAct,surfaceAt,carOk,nearParked,hiratsukaStart,colAt,candidates,showResult,renderDex,FISH,SPEC,waterDir,setDex:(f,s)=>{dexF=f;dexSel=s;},SPOTSALL:()=>SPOTS,get NAVR(){return NAVR},save,load,restoreRide,openWorld,closeWorld,WMv:()=>WM.v};\n})();</script></html>`);
if (html===html0) throw new Error('inject failed');
const W = +(process.env.W||390), H=+(process.env.H||844);
const browser = await chromium.launch({ args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport:{width:W,height:H}, deviceScaleFactor:3, isMobile:true, hasTouch:true });
const logs=[];
page.on('console', m=>logs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', e=>logs.push(`[pageerror] ${e.message}\n${e.stack}`));
await page.route('**/three.min.js', r=>r.fulfill({body:three, contentType:'application/javascript'}));
await page.route(/game\.local\/.+\.pmtiles$/, r=>{const u=new URL(r.request().url());const p=''+ROOT+''+u.pathname;if(!fs.existsSync(p))return r.fulfill({status:404,body:''});const b=fs.readFileSync(p);const m=(r.request().headers()['range']||'').match(/bytes=(\d+)-(\d+)/);if(!m)return r.fulfill({body:b});const a=+m[1],e=Math.min(+m[2],b.length-1);r.fulfill({status:206,body:b.subarray(a,e+1),headers:{'Content-Range':`bytes ${a}-${e}/${b.length}`,'Content-Type':'application/octet-stream'}});});
await page.route(/game\.local\/.+\.json$/, r=>{const u=new URL(r.request().url());{const p=''+ROOT+''+u.pathname;if(!fs.existsSync(p))return r.fulfill({status:404,body:''});r.fulfill({body:fs.readFileSync(p,'utf8'),contentType:'application/json'});}});
await page.route(/game\.local\/.+\.js(\?.*)?$/, r=>{const u=new URL(r.request().url());r.fulfill({body:fs.readFileSync(''+ROOT+''+u.pathname,'utf8'),contentType:'application/javascript'});});
await page.route(/game\.local\/.+\.bin(\?.*)?$/, r=>{const u=new URL(r.request().url());const p=''+ROOT+''+u.pathname;if(!fs.existsSync(p))return r.fulfill({status:404,body:''});r.fulfill({body:fs.readFileSync(p),contentType:'application/octet-stream'});});
await page.route(/game\.local\/.+\.(webp|avif|png|jpg)(\?.*)?$/, r=>{const u=new URL(r.request().url());const p=''+ROOT+''+u.pathname;if(!fs.existsSync(p))return r.fulfill({status:404,body:''});const e=p.split('.').pop();r.fulfill({body:fs.readFileSync(p),contentType:'image/'+(e==='jpg'?'jpeg':e)});});
await page.route('**/fonts.googleapis.com/**', r=>r.abort());
await page.route('http://game.local/', r=>r.fulfill({body:html, contentType:'text/html'}));
await page.goto('http://game.local/'+(process.env.HASH||''));
await page.waitForTimeout(1500);
await page.screenshot({path:SP+'/shot_title.png'});
const script = process.env.SCRIPT ? (await import(process.env.SCRIPT)).default : null;
if (script) await script(page, SP);
console.log(logs.join('\n'));
await browser.close();
