const test=require('node:test'),assert=require('node:assert');
const M=require('../market.js');
const info={kg:1200,L:[12,32],inSeason:true};
const fish=(over)=>Object.assign({id:'aji',kg:.3,L:25,t:600},over||{});
test('鮮度：氷ありは長持ち、48時間で傷む',()=>{const it=fish();assert.ok(M.freshness(it,600+6*60,true)>M.freshness(it,600+6*60,false));assert.strictEqual(M.freshness(it,600+49*60,true),0);assert.ok(M.freshness(it,600,false)===1);});
test('値段：重さ・鮮度・店の種類で変わる',()=>{const ctx={absMin:660,day:3,iced:true};const P=M.PLACES;const mk=P.find(p=>p.kind==='market'),sh=P.find(p=>p.kind==='shop');
  const a=M.priceOf(fish(),info,Object.assign({place:mk},ctx)).yen,b=M.priceOf(fish(),info,Object.assign({place:sh},ctx)).yen;assert.ok(a>b,'市場の方が高い');
  const heavy=M.priceOf(fish({kg:.6}),info,Object.assign({place:mk},ctx)).yen;assert.ok(heavy>a);
  const stale=M.priceOf(fish(),info,{absMin:600+20*60,day:3,iced:false,place:mk}).yen;assert.ok(stale<a);
  assert.ok(M.priceOf(fish(),info,{absMin:600+50*60,day:3,iced:true,place:mk}).spoiled);});
test('相場：日によって変わり、範囲内',()=>{const v=new Set();for(let d=0;d<30;d++){const f=M.dayFactor('aji',d,false);assert.ok(f>=.8*1.08-1e-9&&f<=1.25*1.08+1e-9);v.add(f.toFixed(3));}assert.ok(v.size>20);});
test('持ち物：バケツは5kg まで、クーラーは容量まで',()=>{const S={veh:{cooler:null},money:0};assert.ok(M.add(S,fish({kg:3}),{}));assert.ok(!M.add(S,fish({kg:3}),{}));S.veh.cooler='cooler_l';assert.ok(M.add(S,fish({kg:3}),{cooler_l:30}));assert.strictEqual(S.catch.length,2);});
test('売る：全部売ると持ち物が空になりお金が増える。傷んだ魚は処分',()=>{const S={veh:{cooler:'cooler_s'},money:100,catch:[fish(),fish({t:-5000})]};const pl=M.PLACES[0];
  const r=M.sell(S,pl,{absMin:700,day:1,iced:true},()=>info);assert.strictEqual(r.sold,1);assert.strictEqual(r.spoiled,1);assert.ok(S.money>100);assert.strictEqual(S.catch.length,0);});
test('営業時間',()=>{const mk=M.PLACES.find(p=>p.kind==='market');assert.ok(M.isOpen(mk,6*60));assert.ok(!M.isOpen(mk,13*60));});
test('古いセーブ：クーラーの重さは売れない持ち帰り分として残る',()=>{const S={veh:{fishKg:2.5}};M.migrate(S);assert.strictEqual(S.catch.length,1);assert.ok(S.catch[0].legacy);
  const r=M.sell(S,M.PLACES[0],{absMin:100,day:1,iced:true},()=>info);assert.strictEqual(r.sold,0);assert.strictEqual(S.catch.length,1);});
test('買取所はゲーム座標に変換できる',()=>{const G=require('../geo.js');const P=M.placesIn((a,b)=>G.toGame(a,b));assert.strictEqual(P.length,M.PLACES.length);assert.ok(P.every(p=>isFinite(p.x)&&isFinite(p.y)));});
const ctx0={absMin:660,day:3,iced:true,minOfDay:8*60};
const mkS=()=>{const S={veh:{cooler:'cooler_l'},money:0};M.migrate(S);for(const L of[20,25,30])M.add(S,fish({L,kg:L/100}),{cooler_l:30});return S;};
test('アプリ：どこでも売れて、地域の相場の8割（大きさ・鮮度は同じに効く）',()=>{const S=mkS(),c=S.catch[0];const base=M.priceOf(c,info,Object.assign({},ctx0,{place:{id:'x',kind:'market',region:'shonan'},S:{}})).yen;
  const app=M.appPlace('shonan');const pa=M.priceOf(c,info,Object.assign({},ctx0,{place:app}));assert.ok(pa.yen>0);assert.strictEqual(M.isOpen(app,3*60),true);
  const rate=M.ratePerKg('aji',info,app,ctx0),mrate=M.ratePerKg('aji',info,{id:'zz',kind:'coop',region:'shonan'},ctx0);assert.ok(Math.abs(rate/mrate-.8/.9)<.02);});
test('通し番号で売る：同じ魚は二度売れない、お金は1回分だけ増える',()=>{const S=mkS();const u=S.catch[1].u;const pl=M.appPlace('yokohama');const r1=M.sell(S,pl,ctx0,()=>info,[u]);const m1=S.money;
  const r2=M.sell(S,pl,ctx0,()=>info,[u]);assert.strictEqual(r1.sold,1);assert.strictEqual(r2.sold,0);assert.strictEqual(S.money,m1);assert.strictEqual(S.catch.length,2);assert.ok(!S.catch.some(c=>c.u===u));});
test('お気に入りは一括でも個別でも売らない',()=>{const S=mkS();const u=S.catch[0].u;M.setFav(S,u,true);const r=M.sell(S,M.appPlace(),ctx0,()=>info);assert.strictEqual(r.sold,2);assert.strictEqual(S.catch.length,1);
  assert.strictEqual(M.sell(S,M.appPlace(),ctx0,()=>info,[u]).sold,0);M.setFav(S,u,false);assert.strictEqual(M.sell(S,M.appPlace(),ctx0,()=>info,[u]).sold,1);});
test('見積もりは売らず、売った額と一致する。営業時間外は売れない',()=>{const S=mkS();const mk=Object.assign({region:'yokohama'},M.PLACES.find(p=>p.kind==='market'));const q=M.quote(S,mk,ctx0,()=>info);assert.strictEqual(S.catch.length,3);
  const r=M.sell(S,mk,ctx0,()=>info);assert.strictEqual(r.yen,q.yen);const S2=mkS();const r2=M.sell(S2,mk,Object.assign({},ctx0,{minOfDay:14*60}),()=>info);assert.ok(!r2.ok);assert.strictEqual(S2.catch.length,3);assert.strictEqual(S2.money,0);});
test('大規模魚市場：日・魚種で上下し、高い日はアプリより十分高い。同じ日に売るほど下がる',()=>{const mk={id:'yokohama_central',kind:'market',region:'yokohama'};let hi=0,lo=9;
  for(let d=0;d<60;d++){const v=M.demand(mk,'aji',d,true,0);hi=Math.max(hi,v);lo=Math.min(lo,v);}assert.ok(hi>1.3&&lo<1.0&&lo>=.85,`${lo}-${hi}`);
  assert.ok(M.demand(mk,'aji',5,true,10)<M.demand(mk,'aji',5,true,0));
  const S=mkS();const before=M.ratePerKg('aji',info,mk,Object.assign({},ctx0,{S}));M.sell(S,mk,ctx0,()=>info);assert.ok(M.ratePerKg('aji',info,mk,Object.assign({},ctx0,{S}))<before);});
test('実績：売った匹数・金額・最高額',()=>{const S=mkS();M.sell(S,M.appPlace(),ctx0,()=>info);assert.strictEqual(S.mStats.n,3);assert.strictEqual(S.mStats.yen,S.money);assert.ok(S.mStats.best.yen>0);});
test('移動買取：6〜21時に候補から出て、3時間は同じ場所。夜はいない',()=>{const c=Array.from({length:30},(_,i)=>({x:i*100,y:0,region:'yokohama'}));const a=M.npcBuyers(4,7*60,c,8),b=M.npcBuyers(4,8*60+30,c,8),d=M.npcBuyers(4,10*60,c,8);
  assert.strictEqual(a.length,8);assert.deepStrictEqual(a.map(q=>q.id),b.map(q=>q.id));assert.notDeepStrictEqual(a.map(q=>q.id),d.map(q=>q.id));assert.strictEqual(M.npcBuyers(4,22*60,c).length,0);assert.strictEqual(new Set(a.map(q=>q.id)).size,8);});
test('比較：魚種ごとに高い順、アプリ（各地域）も入る',()=>{const pl=M.placesIn((a,b)=>[b*100,a*100]).map(p=>Object.assign(p,{region:'yokohama'}));const r=M.compare(['aji'],pl,ctx0,()=>info);assert.strictEqual(r.length,1);
  const rows=r[0].rows;for(let i=1;i<rows.length;i++)assert.ok(rows[i-1].rate>=rows[i].rate);assert.ok(rows.some(x=>x.place.kind==='app'));});
test('古いセーブ：番号の無い魚に番号を振る（車の中も）',()=>{const S={catch:[{id:'aji',kg:.2,L:20,t:0}],veh:{owned:[{catch:[{id:'saba',kg:.4,L:30,t:0}]}]}};M.migrate(S);assert.ok(S.catch[0].u>0);assert.ok(S.veh.owned[0].catch[0].u>0);assert.notStrictEqual(S.catch[0].u,S.veh.owned[0].catch[0].u);});
